#!/bin/bash

pingf(){
	ping -W 1 -i 0.2 -c 1 -s 1 $IP &> /dev/null;
	if [ $? -eq 0 ]; then
		echo "$IP is running."
	else
		echo "$IP is down."
	fi
}

if [ -n "$2" ] && [ -n "$3" ]; then
	for i in `seq $2 $3`; do
		IP="$1.$i"
		pingf 
	done
else
	echo "useage: $0 preip num num"
fi		
